FROM eclipse-temurin:11
ARG JAR_FILE=./target/*.jar
COPY ${JAR_FILE} app.jar

ARG SECURE_KEY_MANAGER_PASSWORD
ARG SECURE_KEY_MANAGER_APP_KEY

ENV SECURE_KEY_MANAGER_PASSWORD=$SECURE_KEY_MANAGER_PASSWORD \
    SECURE_KEY_MANAGER_APP_KEY=$SECURE_KEY_MANAGER_APP_KEY

ENTRYPOINT ["java", "-jar", "/app.jar"]
